import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import { RootProvider } from '@/app/providers/root-provider';
import '@/app/styles/globals.css';
import { Header } from '@/widgets/header';

const raleway = Montserrat({
	subsets: ['latin'],
	display: 'swap',
	weight: ['400', '500', '600', '700'],
	variable: '--font-raleway',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	return (
		<html lang={locale} suppressHydrationWarning>
			<body className={`${raleway.variable}`}>
				<RootProvider>
					<Header />
					<main className='flex flex-col gap-24'>{children}</main>
				</RootProvider>
			</body>
		</html>
	);
}
