import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';

import { RootProvider } from '@/app/providers/root-provider';
import '@/app/styles/globals.css';
import { Header } from '@/widgets/header';

const raleway = Raleway({
	subsets: ['latin'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={raleway.className}>
				<RootProvider>
					<Header />
					<main>{children}</main>
				</RootProvider>
			</body>
		</html>
	);
}
